CREATE OR REPLACE PIPE DEV_BRONZE.PARKING.OCR_DATA_PIPE auto_ingest=true as 
COPY INTO DEV_BRONZE.PARKING.OCR_DATA
FROM @dev_common.utilities.s3_stage/ocr/
FILE_FORMAT = (
TYPE = 'CSV'
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  PARSE_HEADER = TRUE
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
)
MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE;