/*Updates the API key for Vehicle Databases and integrates it into the current External Access*/
ALTER NOTEBOOK DEV_BI.BI.LICENSEPLATEAPI
  SET SECRETS = ('VEHICLE_API_KEY' = DEV_BRONZE.PARKING.VEHICLE_API_KEY);

ALTER EXTERNAL ACCESS INTEGRATION MY_EAI
  SET ALLOWED_AUTHENTICATION_SECRETS = (DEV_BRONZE.PARKING.VEHICLE_API_KEY);

-- attach the EAI + secret to the notebook
ALTER NOTEBOOK DEV_BRONZE.PARKING.<NOTEBOOK_NAME>
  SET EXTERNAL_ACCESS_INTEGRATIONS = (MY_EAI),
      SECRETS = ('VEHICLE_API_KEY' = DEV_BRONZE.PARKING.VEHICLE_API_KEY);

      SHOW NOTEBOOKS IN SCHEMA DEV_BRONZE.PARKING;
