CREATE OR REPLACE TABLE PARKING_MONTHLY_SNAPSHOT AS

WITH PARKINGDATA AS (
  SELECT
    DATE_TRUNC('month', TO_DATE(f.FK_EXITDATE::VARCHAR,'YYYYMMDD')) AS SNAPSHOT_MONTH,
    d.CARPARKLOCATION,
    f.REVENUE,
    f.PLATENO,
    f.FK_PARKINGCUSTOMER,
    f.ERRORCODE
  FROM PROD_GOLD.PARKING.DIM_PARKINGATTRIBUTES AS d
  JOIN PROD_GOLD.PARKING.FACT_PARKING           AS f
    ON d.pk_parkingattributes = f.fk_parkingattributes
  WHERE d.CARPARKLOCATION IN ('Terminal 1 Parking Plaza','Terminal 2 Parking Plaza', 'Terminal 1 Valet', 'Terminal 2 Valet')
  AND f.ERRORCODE = ''
),

TXN_SNAPSHOT AS (
  SELECT
    SNAPSHOT_MONTH,
    SUM( CASE WHEN CARPARKLOCATION = 'Terminal 1 Parking Plaza' THEN REVENUE ELSE 0 END ) AS T1_PLAZA_REVENUE,
    SUM( CASE WHEN CARPARKLOCATION = 'Terminal 2 Parking Plaza' THEN REVENUE ELSE 0 END ) AS T2_PLAZA_REVENUE,
    SUM( CASE WHEN CARPARKLOCATION = 'Terminal 1 Valet' THEN REVENUE ELSE 0 END ) AS T1_VALET_REVENUE,
    SUM( CASE WHEN CARPARKLOCATION = 'Terminal 2 Valet' THEN REVENUE ELSE 0 END ) AS T2_VALET_REVENUE,
    SUM(REVENUE) AS TOTAL_REVENUE,
    COUNT_IF(CARPARKLOCATION = 'Terminal 1 Parking Plaza') AS T1_PLAZA_TXN_COUNT,
    COUNT_IF(CARPARKLOCATION = 'Terminal 2 Parking Plaza') AS T2_PLAZA_TXN_COUNT,
    COUNT_IF(CARPARKLOCATION = 'Terminal 1 Valet') AS T1_VALET_TXN_COUNT,
    COUNT_IF(CARPARKLOCATION = 'Terminal 2 Valet') AS T2_VALET_TXN_COUNT,
    COUNT(*) AS TOTAL_TXN_COUNT,

    /*Count of distinct license plates by parking lot location */
    COUNT(DISTINCT IFF(CARPARKLOCATION = 'Terminal 1 Parking Plaza', PLATENO, NULL)) AS DISTINCT_T1_PLAZA_PLATENO,
    COUNT(DISTINCT IFF(CARPARKLOCATION = 'Terminal 2 Parking Plaza', PLATENO, NULL)) AS DISTINCT_T2_PLAZA_PLATENO,
    COUNT(DISTINCT IFF(CARPARKLOCATION = 'Terminal 1 Valet', PLATENO, NULL)) AS DISTINCT_T1_VALET_PLATENO,
    COUNT(DISTINCT IFF(CARPARKLOCATION = 'Terminal 2 Valet', PLATENO, NULL)) AS DISTINCT_T2_VALET_PLATENO,

/*All distinct plates from all transactions*/
    COUNT(DISTINCT PLATENO) AS TOTAL_DISTINCT_PLATENO,

      /* Count of distinct parking customer foreign keys by parking lot */
    COUNT(DISTINCT IFF(CARPARKLOCATION = 'Terminal 1 Parking Plaza', FK_PARKINGCUSTOMER, NULL)) AS DISTINCT_T1_PLAZA_PARKINGCUSTOMER,
    COUNT(DISTINCT IFF(CARPARKLOCATION = 'Terminal 2 Parking Plaza', FK_PARKINGCUSTOMER, NULL)) AS DISTINCT_T2_PLAZA_PARKINGCUSTOMER,
    COUNT(DISTINCT IFF(CARPARKLOCATION = 'Terminal 1 Valet', FK_PARKINGCUSTOMER, NULL)) AS DISTINCT_T1_VALET_PARKINGCUSTOMER,
    COUNT(DISTINCT IFF(CARPARKLOCATION = 'Terminal 2 Valet', FK_PARKINGCUSTOMER, NULL)) AS DISTINCT_T2_VALET_PARKINGCUSTOMER,

    /* Counts all distinct ParkingCustomer Foreign Keys to get a TOTAL_DISTINCT_PARKINGCUSTOMERS */
    COUNT(DISTINCT FK_PARKINGCUSTOMER) AS TOTAL_DISTINCT_PARKINGCUSTOMERS

  FROM PARKINGDATA
  GROUP BY SNAPSHOT_MONTH
),

----------------------------------------------- Average Vehicle Value by Carparklocation ---------------------------------------

STAGE_SAMPLEDATA AS (
  SELECT
    DATE_TRUNC('month', TO_DATE(f.FK_ENTRYDATE::VARCHAR,'YYYYMMDD')) AS SNAPSHOT_MONTH,
    d.CLEAN_MARKET_VALUE,
    f.CARPARKLOCATION
  FROM DEV_SILVER.PARKING.PARKING_VEHICLE_VALUE  AS d
  JOIN DEV_BRONZE.PARKING.MONTHLY_TXN_SAMPLE AS f
    ON d.LICENSE_PLATE_NUMBER = f.PLATENO
),

/*Creates an average vehicle value snapshot by taking the sample staging data and joining it with the cleaned vehicle value from DEV_SILVER to get a vehicle value by parking lot location. 
This view is then joined back to the revenue snapshot to get a full snapshot table of both all transaction revenue and a sample AVG. vehicle value.*/

AVG_VEHICLE_VALUE_SNAPSHOT AS (
  SELECT
    SNAPSHOT_MONTH,
    AVG( CASE WHEN CARPARKLOCATION = 'Terminal 1 Parking Plaza' THEN CLEAN_MARKET_VALUE END ) AS T1_PLAZA_SAMPLE_AVG_VEHICLE_RETAIL_VALUE,
    AVG( CASE WHEN CARPARKLOCATION = 'Terminal 2 Parking Plaza' THEN CLEAN_MARKET_VALUE END ) AS T2_PLAZA_SAMPLE_AVG_VEHICLE_RETAIL_VALUE,
    AVG( CASE WHEN CARPARKLOCATION = 'Terminal 1 Valet' THEN CLEAN_MARKET_VALUE END ) AS T1_VALET_SAMPLE_AVG_VEHICLE_RETAIL_VALUE,
    AVG( CASE WHEN CARPARKLOCATION = 'Terminal 2 Valet' THEN CLEAN_MARKET_VALUE END ) AS T2_VALET_SAMPLE_AVG_VEHICLE_RETAIL_VALUE

  FROM STAGE_SAMPLEDATA
  GROUP BY SNAPSHOT_MONTH
)

/*Joins the 2 snapshot tables on SNAPSHOT_MONTH to get revenue and sample average vehicle value together*/
SELECT
  TXN.*,
  AV.T2_VALET_SAMPLE_AVG_VEHICLE_RETAIL_VALUE, 
  AV.T1_VALET_SAMPLE_AVG_VEHICLE_RETAIL_VALUE, 
  AV.T1_PLAZA_SAMPLE_AVG_VEHICLE_RETAIL_VALUE, 
  T2_PLAZA_SAMPLE_AVG_VEHICLE_RETAIL_VALUE
  
FROM TXN_SNAPSHOT AS TXN
LEFT JOIN AVG_VEHICLE_VALUE_SNAPSHOT AS AV
  ON TXN.SNAPSHOT_MONTH = AV.SNAPSHOT_MONTH
ORDER BY TXN.SNAPSHOT_MONTH;

-------------------------- Every parking transaction by parking lot location ---------------------------------------
/*
WITH PARKINGDATA AS (
  SELECT
    DATE_TRUNC('month', TO_DATE(f.FK_EXITDATE::VARCHAR, 'YYYYMMDD')) AS SNAPSHOT_MONTH,
    d.CARPARKLOCATION,
    f.REVENUE
  FROM PROD_GOLD.PARKING.DIM_PARKINGATTRIBUTES AS d
  JOIN PROD_GOLD.PARKING.FACT_PARKING           AS f
    ON d.pk_parkingattributes = f.fk_parkingattributes
  WHERE d.CARPARKLOCATION IN ('Terminal 1 Parking Plaza','Terminal 2 Parking Plaza','Terminal 1 Valet','Terminal 2 Valet')
  AND DATE_TRUNC('month', TO_DATE(f.FK_EXITDATE::VARCHAR, 'YYYYMMDD')) = DATE '2025-06-01'
)

SELECT 
    SNAPSHOT_MONTH,
    
    REVENUE,
    
    CASE WHEN CARPARKLOCATION = 'Terminal 1 Parking Plaza' THEN REVENUE ELSE 0 END AS T1_PLAZA_REVENUE,
    
    CASE WHEN CARPARKLOCATION = 'Terminal 2 Parking Plaza' THEN REVENUE ELSE 0 END AS T2_PLAZA_REVENUE,
    
    CASE WHEN CARPARKLOCATION = 'Terminal 1 Valet' THEN REVENUE ELSE 0 END AS T1_VALET_REVENUE,
    
    CASE WHEN CARPARKLOCATION = 'Terminal 2 Valet' THEN REVENUE ELSE 0 END AS T2_VALET_REVENUE
    
FROM PARKINGDATA
*/